name: Update README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:

  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install
      - run: npm run update-readme
        env:
          INSTAGRAM_API_KEY: ${{ secrets.INSTAGRAM_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m ":calendar: Update README with latest info"
          git push origin main
